all:
  hosts:
    dgx:

  children:
    dgxs:
      hosts:
        dgx-[1:8]:
    dell:
      hosts:
        dell-login1:
        dell-login2:
        dell-manager1:
        dell-manager2:
        dell-manager3:
        dell-web1:
        dell-web2:
    rtx:
      hosts:
        dell-rtx1:
        dell-rtx2:
    manager_server:
      hosts:
        dell-manager1:
        dell-manager2:
        dell-manager3:
