all:
  children:
    vars:
      ansible_become_pass: "abc123###"

    ypy:
      hosts:
        ypy-[1:8]:
        ypy-[13:18]:
    ypy2:
      hosts:
        ypy-[13:18]:

    xjxh:
      vars:
        ansible_become_pass: "dz112233"
      hosts:
        dsw:
        dsw-pha[1:2]:
      children:
        chia-forks-wulaoshi:
          hosts:
            wulaoshi-[211:219]:
        chia-forks3:
          hosts:
            dsw-3:
            dsw-2:
            dsw-9:
            dsw-8:
            dsw-6:
            dsw-7:
            dsw-10:
            dsw-4:
            dsw-11:
            dsw-5:
            dsw-34:
        chia-forks2:
          hosts:
            dsw-16:
            dsw-27:
            dsw-19:
            dsw-26:
            dsw-12:
            dsw-17:
            dsw-15:
            dsw-14:
            dsw-13:
            dsw-28:
            dsw-33:
            dsw-18:
            dsw-29:
            dsw-32:
            dsw-35:
        chia-forks:
          hosts:
            # wulaoshi-[211:220]:
            # dsw-1:
            dsw-2:
            dsw-3:
            dsw-4:
            dsw-5:
            dsw-6:
            dsw-7:
            dsw-8:
            dsw-9:
            dsw-10:
            dsw-11:
            dsw-12:
            dsw-13:
            dsw-14:
            dsw-15:
            dsw-16:
            dsw-17:
            dsw-18:
            dsw-19:
            dsw-26:
            dsw-27:
            dsw-28:
            dsw-29:
            dsw-32:
            dsw-33:
            dsw-34:
            dsw-35:
        wulaoshi:
          vars:
            ansible_become_pass: "xjxh123###"
          hosts:
            wulaoshi-[211:220]:
        dswchia:
          hosts:
            dsw-1:
            dsw-2:
            dsw-3:
            dsw-4:
            dsw-5:
            dsw-6:
            dsw-7:
            dsw-8:
            dsw-9:
            dsw-10:
            dsw-11:
            dsw-12:
            dsw-13:
            dsw-14:
            dsw-15:
            dsw-16:
            dsw-17:
            dsw-18:
            dsw-19:
            dsw-26:
            dsw-27:
            dsw-28:
            dsw-29:
            dsw-32:
            dsw-33:
            dsw-34:
            dsw-35:
    dgx:
      hosts:
        dgx[1:8]:
    jinhuo:
      children:
        nas:
          hosts:
            nas[1:8]:
    huang:
      hosts:
        huang-14:
        huang-16:
        huang-18:
        huang-20:
        huang-22:
        # huang-24:
        huang-26:
        huang-28:
        huang-30:
        huang-32:
        huang-34:
        huang-36:
        huang-38:
        huang-40:
        huang-42:
        huang-44:
        huang-46:
        huang-48:
        huang-50:
        huang-52:
        huang-64:
        huang-66:
        huang-68:
        huang-70:
        huang-72:
        huang-74:
        huang-76:
        huang-78:
        huang-80:
        huang-82:
        # huang-84:
        huang-86:
        huang-88:
        huang-90:
        huang-92:
        huang-94:
        huang-96:
        huang-98:
        huang-100:
        huang-102:
        huang-104:
        huang-106:
        huang-108:
        huang-110:
      children:
        test-harvester:
          hosts:
            huang-14:
            huang-[16:22:2]:
            huang-[26:52:2]:
            huang-[64:82:2]:
            huang-[86:98:2]:
            huang-[102:110:2]:
